# Generated by Django 3.1.2 on 2020-10-02 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Book Title")),
                ("description", models.CharField(max_length=255, verbose_name="Book Description")),
                ("genre", models.CharField(max_length=255, verbose_name="Genre")),
                ("isbn", models.CharField(max_length=20, verbose_name="ISBN")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Book Author")),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["id"],
            },
        ),
    ]
