# Generated by Django 3.1.2 on 2020-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
        ),
    ]
