version: "3.7"

services:
 django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        USER_ID: 1000
        USER_GROUP: 1000
        DEV: 1
    image: mirumee_book_api
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      USE_DOCKER: "yes"
      IPYTHONDIR: /app/.ipython
      DJANGO_READ_DOT_ENV_FILE: 1
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

 postgres:
    image: postgres:12.1-alpine
    volumes:
      - book_api_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  book_api_postgres_data: {}
