[tool.poetry]
name = "book_api"
version = "0.5.0"
authors = []
description = ""
packages = []

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"
wheel = "^0.35.1"
pip = "^20.2.2"
django-environ = "^0.4.5"
